image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - build
  - test
  - review
  - production

Build system:
  stage: build

  script:
    - echo "Building..."

Code Linting:
  stage: test

  script:
    - echo "Code Linting...."

Unit tests:
  stage: test

  script:
    - echo "Running Unit tests..."

Deploy to production: 
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY


    only:
      - main
      - review